### ISSUE TITLE
Keyboard Shortcut?

### ISSUE THREAD

**Issue by humanplayer2** [fthx/sticky-terminal#1]
**First, praise:** 

I'm super thrilled about this extension! I use tiling on Pop!_OS, and I've been looking for a way to get a "drop down file manager" window up and running---and I can use this extension for exactly that! It's like you've implemented the i3 scratchpad, restricted to a single app (per extension instance---one could of course just have a number of variants of the extension installed). Sweet! This is a real omission in Pop!'s COSMIC.

**Second, a question:** 
My workflow is quite keyboard driven. I would love to be able to set a shortcut for the toggle. 

_Is there a command that activates the toggle?_

I looked through the code, but it wasn't obvious to me.

**Comment by fthx** [comment]
There's no shortcut. But this could be implemented.
To be honest, I do not use this ext anymore (I use a manual GNOME way, right-click on header bar etc.) so I won't spend more time on it. But I'm fully open to PR, of course.

**Comment by humanplayer2** [comment]
Fair enough! 
I searched around for the commands I would need, and bumped into the [run-or-raise](https://github.com/CZ-NIC/run-or-raise) extension which covers the need I have.
